import Foundation

/// The native Phase 1 method used when a depth-aware renderer is unavailable.
/// It deliberately names an editable Final Cut transform recipe rather than a
/// renderer, command, or baked-media operation.
public enum LivingStillMotionMethod: String, Codable, CaseIterable, Sendable {
    case nativePushInPan = "native-push-in-pan"
}

public enum LivingStillDepthFlowStatus: String, Codable, CaseIterable, Sendable {
    case deferredUnavailable = "deferred-unavailable"
}

/// Pixel provenance for the native fallback.  No new image/video asset is
/// generated by this composition; the selected still remains the source.
public enum LivingStillPixelClassification: String, Codable, CaseIterable, Sendable {
    case sourceMediaPreserved = "source-media-preserved"
    case noBakedPixels = "no-baked-pixels"
}

public struct LivingStillTransformKeyframe: Codable, Equatable, Sendable {
    public var timeSeconds: Double
    public var scale: Double
    public var panX: Double
    public var panY: Double

    public init(timeSeconds: Double, scale: Double, panX: Double, panY: Double) {
        self.timeSeconds = timeSeconds
        self.scale = scale
        self.panX = panX
        self.panY = panY
    }
}

public struct LivingStillColorKeyframe: Codable, Equatable, Sendable {
    public var timeSeconds: Double
    public var enrichment: Double

    public init(timeSeconds: Double, enrichment: Double) {
        self.timeSeconds = timeSeconds
        self.enrichment = enrichment
    }
}

public struct LivingStillOpacityKeyframe: Codable, Equatable, Sendable {
    public var timeSeconds: Double
    public var opacity: Double

    public init(timeSeconds: Double, opacity: Double) {
        self.timeSeconds = timeSeconds
        self.opacity = opacity
    }
}

public struct LivingStillComposition: Codable, Equatable, Sendable {
    public let effectID: EffectID
    public let representation: RepresentationClass
    public let sourceIdentity: SourceIdentity
    public let preservesOriginal: Bool
    public let pixelClassification: LivingStillPixelClassification
    public let fallback: String
    public let nativeFallbackEnabled: Bool
    public let motionMethod: LivingStillMotionMethod
    public let depthFlowStatus: LivingStillDepthFlowStatus
    public let easing: Easing
    public let durationSeconds: Double
    public let fadeDurationSeconds: Double
    public let transformKeyframes: [LivingStillTransformKeyframe]
    public let colorKeyframes: [LivingStillColorKeyframe]
    public let opacityKeyframes: [LivingStillOpacityKeyframe]

    public init(effectID: EffectID,
                representation: RepresentationClass,
                sourceIdentity: SourceIdentity,
                preservesOriginal: Bool,
                pixelClassification: LivingStillPixelClassification,
                fallback: String,
                nativeFallbackEnabled: Bool,
                motionMethod: LivingStillMotionMethod,
                depthFlowStatus: LivingStillDepthFlowStatus,
                easing: Easing,
                durationSeconds: Double,
                fadeDurationSeconds: Double,
                transformKeyframes: [LivingStillTransformKeyframe],
                colorKeyframes: [LivingStillColorKeyframe],
                opacityKeyframes: [LivingStillOpacityKeyframe]) {
        self.effectID = effectID
        self.representation = representation
        self.sourceIdentity = sourceIdentity
        self.preservesOriginal = preservesOriginal
        self.pixelClassification = pixelClassification
        self.fallback = fallback
        self.nativeFallbackEnabled = nativeFallbackEnabled
        self.motionMethod = motionMethod
        self.depthFlowStatus = depthFlowStatus
        self.easing = easing
        self.durationSeconds = durationSeconds
        self.fadeDurationSeconds = fadeDurationSeconds
        self.transformKeyframes = transformKeyframes
        self.colorKeyframes = colorKeyframes
        self.opacityKeyframes = opacityKeyframes
    }

    /// Convenience aliases for callers that treat each native edit as a
    /// channel rather than an implementation-specific keyframe collection.
    public var transform: [LivingStillTransformKeyframe] { transformKeyframes }
    public var color: [LivingStillColorKeyframe] { colorKeyframes }
    public var opacity: [LivingStillOpacityKeyframe] { opacityKeyframes }
    public var source: SourceIdentity { sourceIdentity }
    public var duration: Double { durationSeconds }
    public var noBakedPixels: Bool { pixelClassification == .noBakedPixels }
    public var sourceMediaPreserved: Bool { preservesOriginal }
    public var usesBakedPixels: Bool { false }
    public var isNativeFallback: Bool { nativeFallbackEnabled && representation == .fcpxmlNative }
    public var fallbackLabel: String { fallback }
}

public enum LivingStillCompositionError: Error, LocalizedError, Equatable, Sendable {
    case wrongEffect(EffectID)
    case wrongRepresentation(RepresentationClass)
    case missingParameter(String)
    case wrongParameterType(String)
    case outOfRange(String)
    case nonFinite(String)
    case unknownMotionMethod(String)
    case unknownDepthFlowStatus(String)
    case unknownEasing(String)
    case invalidSource(String)
    case invalidComposition(String)

    public var errorDescription: String? {
        switch self {
        case .wrongEffect(let id): return "Living Still composition requires motion.living_still, got " + id.rawValue
        case .wrongRepresentation(let representation): return "Living Still composition requires fcpxml_native, got " + representation.rawValue
        case .missingParameter(let name): return "Living Still composition is missing parameter " + name
        case .wrongParameterType(let name): return "Living Still composition parameter " + name + " has the wrong type"
        case .outOfRange(let name): return "Living Still composition parameter " + name + " is outside its bounded range"
        case .nonFinite(let name): return "Living Still composition parameter " + name + " is not finite"
        case .unknownMotionMethod(let value): return "Unknown Living Still motion method " + value
        case .unknownDepthFlowStatus(let value): return "Unknown Living Still depth-flow status " + value
        case .unknownEasing(let value): return "Unknown Living Still easing " + value
        case .invalidSource(let reason): return "Invalid Living Still source: " + reason
        case .invalidComposition(let reason): return "Invalid Living Still composition: " + reason
        }
    }
}

public enum LivingStillCompositionBuilder {
    private static let fallback = "native-push-in-pan-color-enrichment-fade-to-black"
    private static let parameterNames: Set<String> = [
        "durationSeconds", "pushInScaleStart", "pushInScaleEnd", "panX", "panY",
        "colorEnrichment", "opacityStart", "opacityEnd", "fadeDurationSeconds",
        "preserveOriginal", "nativeFallbackEnabled", "depthFlowStatus", "motionMethod", "easing"
    ]

    public static func build(from plan: EffectPlan) throws -> LivingStillComposition {
        guard plan.effectID == .livingStill else { throw LivingStillCompositionError.wrongEffect(plan.effectID) }
        try CapabilityGate().require(plan, capability: .localOnlyPreview)
        guard plan.representation == .fcpxmlNative else {
            throw LivingStillCompositionError.wrongRepresentation(plan.representation)
        }
        guard plan.generatedAssets.isEmpty else {
            throw LivingStillCompositionError.invalidComposition("native fallback must not declare generated assets")
        }
        guard plan.fallback == fallback else {
            throw LivingStillCompositionError.invalidComposition("fallback metadata does not match the native fallback")
        }
        guard plan.previewStrategy == "native-editable-push-in-pan-preview" else {
            throw LivingStillCompositionError.invalidComposition("preview metadata does not describe the native fallback")
        }
        let unknown = plan.parameters.keys.filter { !parameterNames.contains($0) }.sorted()
        if let first = unknown.first {
            throw LivingStillCompositionError.invalidComposition("unknown parameter " + first)
        }
        let source = try sourceIdentity(from: plan.selectionToken)

        let duration = try number("durationSeconds", in: plan.parameters, range: 0.1...30)
        let startScale = try number("pushInScaleStart", in: plan.parameters, range: 0.1...4)
        let endScale = try number("pushInScaleEnd", in: plan.parameters, range: 0.1...4)
        guard endScale >= startScale else { throw LivingStillCompositionError.invalidComposition("push-in end scale must not be below start scale") }
        let panX = try number("panX", in: plan.parameters, range: -0.5...0.5)
        let panY = try number("panY", in: plan.parameters, range: -0.5...0.5)
        let colorEnrichment = try number("colorEnrichment", in: plan.parameters, range: 0...0.5)
        let opacityStart = try number("opacityStart", in: plan.parameters, range: 0...1)
        let opacityEnd = try number("opacityEnd", in: plan.parameters, range: 0...1)
        guard opacityEnd <= opacityStart else { throw LivingStillCompositionError.invalidComposition("fade end opacity must not exceed start opacity") }
        let fadeDuration = try number("fadeDurationSeconds", in: plan.parameters, range: 0.05...2)
        guard fadeDuration <= duration else { throw LivingStillCompositionError.invalidComposition("fade duration exceeds movement duration") }
        let preservesOriginal = try bool("preserveOriginal", in: plan.parameters)
        guard preservesOriginal else { throw LivingStillCompositionError.invalidComposition("the native fallback must preserve the original still") }
        let nativeFallbackEnabled = try bool("nativeFallbackEnabled", in: plan.parameters)
        guard nativeFallbackEnabled else { throw LivingStillCompositionError.invalidComposition("native fallback is disabled") }

        let depthFlowStatus = try depthFlowStatus("depthFlowStatus", in: plan.parameters)
        let motionMethod = try motionMethod("motionMethod", in: plan.parameters)
        let easing = try easing("easing", in: plan.parameters)

        let fadeStart = duration - fadeDuration
        let opacityKeyframes: [LivingStillOpacityKeyframe]
        if fadeStart <= 0 {
            opacityKeyframes = [
                LivingStillOpacityKeyframe(timeSeconds: 0, opacity: opacityStart),
                LivingStillOpacityKeyframe(timeSeconds: duration, opacity: opacityEnd)
            ]
        } else {
            opacityKeyframes = [
                LivingStillOpacityKeyframe(timeSeconds: 0, opacity: opacityStart),
                LivingStillOpacityKeyframe(timeSeconds: fadeStart, opacity: opacityStart),
                LivingStillOpacityKeyframe(timeSeconds: duration, opacity: opacityEnd)
            ]
        }

        return LivingStillComposition(
            effectID: .livingStill,
            representation: .fcpxmlNative,
            sourceIdentity: source,
            preservesOriginal: preservesOriginal,
            pixelClassification: .noBakedPixels,
            fallback: fallback,
            nativeFallbackEnabled: nativeFallbackEnabled,
            motionMethod: motionMethod,
            depthFlowStatus: depthFlowStatus,
            easing: easing,
            durationSeconds: duration,
            fadeDurationSeconds: fadeDuration,
            transformKeyframes: [
                LivingStillTransformKeyframe(timeSeconds: 0, scale: startScale, panX: 0, panY: 0),
                LivingStillTransformKeyframe(timeSeconds: duration, scale: endScale, panX: panX, panY: panY)
            ],
            colorKeyframes: [
                LivingStillColorKeyframe(timeSeconds: 0, enrichment: 0),
                LivingStillColorKeyframe(timeSeconds: duration, enrichment: colorEnrichment)
            ],
            opacityKeyframes: opacityKeyframes
        )
    }

    private static func sourceIdentity(from token: SelectionToken) throws -> SourceIdentity {
        guard token.selectionType == .singleClip, token.clipIDs.count == 1, token.sourceIdentities.count == 1,
              let source = token.sourceIdentities.first, source.itemID == token.clipIDs[0], !source.itemID.isEmpty else {
            throw LivingStillCompositionError.invalidSource("exactly one typed source identity is required")
        }
        let path = source.canonicalPath
        guard path.hasPrefix("/"), !path.isEmpty, !path.split(separator: "/").contains(".."),
              URL(fileURLWithPath: path).standardizedFileURL.path == path,
              URL(fileURLWithPath: path).resolvingSymlinksInPath().standardizedFileURL.path == path,
              !path.unicodeScalars.contains(where: { ";&|`$()<>*?{}\n\r".unicodeScalars.contains($0) }) else {
            throw LivingStillCompositionError.invalidSource("source path must be absolute, canonical, and shell-safe")
        }
        guard source.sha256.count == 64,
              source.sha256.unicodeScalars.allSatisfy({ scalar in
                  (scalar.value >= 48 && scalar.value <= 57) || (scalar.value >= 97 && scalar.value <= 102)
              }) else {
            throw LivingStillCompositionError.invalidSource("source SHA-256 must be lowercase hexadecimal")
        }
        return source
    }

    private static func value(_ name: String, in parameters: [String: ParameterValue]) throws -> ParameterValue {
        guard let value = parameters[name] else { throw LivingStillCompositionError.missingParameter(name) }
        return value
    }

    private static func bool(_ name: String, in parameters: [String: ParameterValue]) throws -> Bool {
        guard case .boolean(let value) = try value(name, in: parameters) else {
            throw LivingStillCompositionError.wrongParameterType(name)
        }
        return value
    }

    private static func string(_ name: String, in parameters: [String: ParameterValue]) throws -> String {
        guard case .string(let value) = try value(name, in: parameters) else {
            throw LivingStillCompositionError.wrongParameterType(name)
        }
        return value
    }

    private static func number(_ name: String,
                               in parameters: [String: ParameterValue],
                               range: ClosedRange<Double>) throws -> Double {
        let value = try value(name, in: parameters)
        let number: Double
        switch value {
        case .number(let candidate): number = candidate
        case .integer(let candidate): number = Double(candidate)
        default: throw LivingStillCompositionError.wrongParameterType(name)
        }
        guard number.isFinite else { throw LivingStillCompositionError.nonFinite(name) }
        guard range.contains(number) else { throw LivingStillCompositionError.outOfRange(name) }
        return number
    }

    private static func motionMethod(_ name: String, in parameters: [String: ParameterValue]) throws -> LivingStillMotionMethod {
        let value = try string(name, in: parameters)
        guard let method = LivingStillMotionMethod(rawValue: value) else {
            throw LivingStillCompositionError.unknownMotionMethod(value)
        }
        return method
    }

    private static func depthFlowStatus(_ name: String, in parameters: [String: ParameterValue]) throws -> LivingStillDepthFlowStatus {
        let value = try string(name, in: parameters)
        guard let status = LivingStillDepthFlowStatus(rawValue: value) else {
            throw LivingStillCompositionError.unknownDepthFlowStatus(value)
        }
        return status
    }

    private static func easing(_ name: String, in parameters: [String: ParameterValue]) throws -> Easing {
        let value = try string(name, in: parameters)
        guard let easing = Easing(rawValue: value) else {
            throw LivingStillCompositionError.unknownEasing(value)
        }
        return easing
    }
}
